### ISSUE TITLE
Unallocated runes to first non OP_RETURN

### ISSUE THREAD

**Issue by JoeyKhd** [magicoss/runestone-lib#56]
Magic Eden is using the pointer way of to send Runes. Perhaps we can add that to tryDecodeRunestone ?

![image](https://github.com/magicoss/runestone-lib/assets/23193015/18471550-235e-49ee-ba92-f6794ec62273)

Here is an example transaction: https://mempool.space/tx/626c21452e512476da878a23958bf05ac7374efd9bec4a90a4f267f2f6d598ee

Where based on Magic Eden, there is a transfer of 4200 RSIC.

**Comment by summraznboi** [comment]
tryDecodeRunestone is decoding what is actually found in the encoded runestone, so it makes sense for this method to not return anything.

**Comment by summraznboi** [comment]
@jeasonstudio This is a great way to bootstrap ord's Rust SOT implementation into Javascript! However, the indexer in this repo actually uses different reorg logic, so its not a full copy-paste reimplementation.
