### ISSUE TITLE
buffer.at is not a function

### ISSUE THREAD

**Issue by daorren** [magicoss/runestone-lib#63]
hi, first ty for providing this runes js lib
and I met a problem while execute your example in readme

https://github.com/magicoss/runestone-lib/blob/main/src/rune.ts#L85

here is a buffer.at function
is this a valid js function

FYI 
node version=14.21.2

**Comment by summraznboi** [comment]
I think you need at least node 16, please try that and see if it still works

**Comment by summraznboi** [comment]
Yes, Buffer is a subclass of Uint8Array for node v16, which has at method: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/at
